@baseUrl = http://localhost:8081/api

GET {{baseUrl}}/employees/

###
# @name create_employee
POST {{baseUrl}}/employees/
Content-Type: application/json

{
  "name": "Valaki",
  "level": "Godlike",
  "position": "Joker"
}

# Save the employee's id:
{{
  $global.id=response.parsedBody._id
}}


###
PATCH {{baseUrl}}/employees/{{$global.id}}
Content-Type:  application/json

{
  "name": "asd"
}

###
DELETE {{baseUrl}}/employees/{{$global.id}}

### Test if this will break the pipeline or not
GET {{baseUrl}}/wrongPath

